version: "3.8"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "4036:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    tty: true

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - laravel
    
  php:
    build:
      context: .
      dockerfile: .docker/php/dockerfile
    container_name: php
    depends_on:
      - mysql
    networks:
      - laravel
    ports:
      - 9000
    volumes:
      - ./:/var/www/html
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini


volumes:
  mysql_data: