version: "3.8"
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php
    tty: true
    networks:
      - laravel

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./.docker/php/dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 9000:9000
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prospect_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    networks:
      - laravel

volumes:
  mysql_data: